// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
//    apply from: "config_sign.gradle"

    // https://kotlinlang.org/docs/releases.html#release-details
    // 1.3.72 | 1.3.x last version
    // 1.4.32 | 1.4.x last version
    // 1.5.32 | 1.5.x last version
    // 1.6.21 | 1.6.x last version
    // 1.7.21 | 1.7.x last version
    // 1.8.22 | 1.8.x last version
    // 1.9.25 | 1.9.x last version
    // 2.0.21 | 2.0.x last version
    // 2.1.21 | 2.1.x last version
    // 2.2.10 | 2.2.x last version
    // 不升级最新版，有些太新的库可能还没更新，容易报错
    ext.kotlin_version = "2.1.21"

    dependencies {
//        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${kotlin_version}"
    }
}

plugins {
    //
    // AGP 与 Gradle 对应版本, AGP 与 Android Studio 对应版本（另外 AGP 与 Gradle 对应版本见 `gradle-wrapper.properties`）
    // AGP https://developer.android.com/build/releases/gradle-plugin
    // AGP Older Versions https://developer.android.com/build/releases/gradle-plugin#expandable-1
    // AS                               --> AGP
    // Flamingo | 2022.2.1              --> 3.2-8.0
    // Giraffe | 2022.3.1               --> 3.2-8.1
    // Hedgehog | 2023.1.1              --> 3.2-8.2
    // Iguana | 2023.2.1                --> 3.2-8.3
    // Jellyfish | 2023.3.1             --> 3.2-8.4
    // Koala | 2024.1.1                 --> 3.2-8.5
    // Koala Feature Drop | 2024.1.2    --> 3.2-8.6
    // Ladybug | 2024.2.1               --> 3.2-8.7
    // Ladybug Feature Drop | 2024.2.2  --> 3.2-8.8
    // Meerkat | 2024.3.1               --> 3.2-8.9
    // Meerkat Feature Drop | 2024.3.2  --> 3.2-8.10
    // Narwhal | 2025.1.1               --> 3.2-8.11
    // Narwhal Feature Drop | 2025.1.2  --> 4.0-8.12
    //
    // API 与 AGP 对应版本
    // API Level https://developer.android.com/build/releases/gradle-plugin#api-level-support
    // API  | minimum AS   | minimum AGP
    // 33   | F            | 7.2
    // 34   | H            | 8.1.1
    // 35   | KFD          | 8.6.0
    // 36   | M            | 8.9.0
    // 36.0 | M Patch1     | 8.9.1
    //      | MFD          |
    //      | N            |
    //      | NFD          |
    //
    // 3.6.4 | 3.x.x last version
    // 4.2.2 | 4.x.x last version
    // 7.4.2 | 7.x.x last version | 从 AGP 7.0.0 开始，构建 AAR 时不支持模块直接依赖本地 .aar 文件（不支持子模块包含本地 aar，请使用 maven 远程依赖）
    // 8.1.4 | 支持 AS G 的最高版本
    //
    // API 35 需要 AGP 8.6.0+
//    id "com.android.application" version "8.6.1" apply false // AGP 8.6 需要 AS KFD+
//    id "com.android.library" version "8.6.1" apply false
    // API 36 需要 AGP 8.9.0+
    id "com.android.application" version "8.9.1" apply false // AGP 8.9.1 需要 AS M+
    id "com.android.library" version "8.9.1" apply false
//    id "com.android.application" version "8.10.1" apply false // AGP 8.10 需要 AS MFD+
//    id "com.android.library" version "8.10.1" apply false

    // KGP https://kotlinlang.org/docs/gradle-configure-project.html
    id "org.jetbrains.kotlin.android" version "${kotlin_version}" apply false
    id "org.jetbrains.kotlin.jvm" version "${kotlin_version}" apply false

    // KSP https://github.com/google/ksp/releases
    // 1.9.25-1.0.20
    // 2.0.21-1.0.28
    // 2.1.21-2.0.2
    // 2.2.10-2.0.2
    id "com.google.devtools.ksp" version "${kotlin_version}-2.0.2" apply false

    // Compose Compiler Gradle plugin, kotlin 2.x+ 的 compose 配置
    id "org.jetbrains.kotlin.plugin.compose" version "${kotlin_version}" apply false
}