android {
    sourceSets {
        main {
            // `+=` 追加目录，`=` 会覆盖默认目录
            res.srcDirs += [
                    // 多语言
                    "src/main/res-language",

                    // 拆分存放各模块的资源
                    "src/main/res-splash",
                    "src/main/res-setting",
            ]

//            java.srcDirs += ["src/main/kotlin"]
//            res.srcDirs += ["src/main/res"]
//            assets.srcDirs += ["src/main/assets"]
//            jniLibs.srcDirs += ["src/main/jniLibs"]
//            manifest.srcFile "src/main/AndroidManifest.xml"
        }
        // 这些最终会合并到 main
        // 可以指定不同的 buildTypes / productFlavors 使用不同的资源目录
        debug {
            java.srcDirs += ["src/debug/java"]
            res.srcDirs += ["src/debug/res"]
            manifest.srcFile "src/debug/AndroidManifest.xml"
        }
        release {
            // 这些是 引用占位，空壳代码，因为 main 使用到对应的 debug 代码，加上只为不报错
            java.srcDirs += ["src/placeholders/java/"]
        }
        app {

        }
        github {

        }
//        floatButton {
//            java.srcDirs += ["src/floatButton/java"]
//            res.srcDirs += ["src/floatButton/res"]
//            manifest.srcFile "src/floatButton/AndroidManifest.xml"
//        }
    }
}