
## 使用 Http Client 插件执行
## （AS M 才开始支持，IDEA Ultimate 低版本也自带插件）
## <https://plugins.jetbrains.com/plugin/13121-http-client>

### 登录
POST https://www.wanandroid.com/user/login
Content-Type: application/x-www-form-urlencoded

username=yourusername&password=yourpassword

### 获取用户信息
GET https://www.wanandroid.com/user/lg/userinfo/json
Cookie: JSESSIONID=99999999999999999999999999999999

### 获取 Banner 列表
GET https://www.wanandroid.com/banner/json

### 获取首页置顶文章列表
GET https://www.wanandroid.com/article/top/json

### 获取首页文章列表
GET https://www.wanandroid.com/article/list/0/json?page_size=10
