pluginManagement {
    repositories {
        mavenLocal()
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url "https://jitpack.io" }
        maven { url "https://repo1.maven.org/maven2/" }
        maven { url "https://maven.aliyun.com/repository/gradle-plugin" } // gradlePluginPortal
        maven { url "https://maven.aliyun.com/repository/google" } // google
        maven { url "https://maven.aliyun.com/repository/central" } // mavenCentral
        maven { url "https://maven.aliyun.com/repository/public" } // central + jcenter
        maven { url "https://repo.huaweicloud.com/repository/maven" }
        maven { url "https://mirrors.huaweicloud.com/repository/maven" }
        maven { url "https://mirrors.tencent.com/nexus/repository/maven-public" }
        maven { url "https://mirrors.163.com/maven/repository/maven-central" }
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenLocal()
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
        maven { url "https://repo1.maven.org/maven2/" }
        maven { url "https://maven.aliyun.com/repository/google" } // google
        maven { url "https://maven.aliyun.com/repository/central" } // mavenCentral
        maven { url "https://maven.aliyun.com/repository/public" } // central + jcenter
        maven { url "https://repo.huaweicloud.com/repository/maven" }
        maven { url "https://mirrors.huaweicloud.com/repository/maven" }
        maven { url "https://mirrors.tencent.com/nexus/repository/maven-public" }
        maven { url "https://mirrors.163.com/maven/repository/maven-central" }
    }
}

rootProject.name = "WanAndroid"
include ":app"
//include ":module_lint"
