pluginManagement {
    repositories {
        mavenLocal()
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url "https://jitpack.io" }
        maven { url "https://repo1.maven.org/maven2/" }
        maven { url "https://maven.aliyun.com/repository/gradle-plugin" } // gradlePluginPortal
        maven { url "https://maven.aliyun.com/repository/google" } // google
        maven { url "https://maven.aliyun.com/repository/central" } // mavenCentral
        maven { url "https://maven.aliyun.com/repository/public" } // central + jcenter
        maven { url "https://repo.huaweicloud.com/repository/maven" }
        maven { url "https://mirrors.huaweicloud.com/repository/maven" }
        maven { url "https://mirrors.tencent.com/nexus/repository/maven-public" }
        maven { url "https://mirrors.163.com/maven/repository/maven-central" }
    }
}

dependencyResolutionManagement {
    /**
     RepositoriesMode
     - FAIL_ON_PROJECT_REPOS：严格模式。所有仓库必须在 settings.gradle 中声明。如果在模块级 build.gradle 文件中额外添加了 repositories 块，Gradle 会报错
     - PREFER_PROJECT_REPOS：项目优先模式。模块级 build.gradle 中声明的仓库会覆盖 settings.gradle 中的配置
     - PREFER_SETTINGS_REPOS：设置优先模式（Gradle 6.8+）。优先使用 settings.gradle 中的仓库，但允许模块级添加额外仓库
     */
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenLocal()
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
        maven { url "https://repo1.maven.org/maven2/" }
        maven { url "https://maven.aliyun.com/repository/google" } // google
        maven { url "https://maven.aliyun.com/repository/central" } // mavenCentral
        maven { url "https://maven.aliyun.com/repository/public" } // central + jcenter
        maven { url "https://repo.huaweicloud.com/repository/maven" }
        maven { url "https://mirrors.huaweicloud.com/repository/maven" }
        maven { url "https://mirrors.tencent.com/nexus/repository/maven-public" }
        maven { url "https://mirrors.163.com/maven/repository/maven-central" }
    }
}

rootProject.name = "WanAndroid"
include ":app"
include ':module_utils'
//include ":module_lint"
