plugins {
    id 'java-library'
    id 'org.jetbrains.kotlin.jvm'
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8

    toolchain.languageVersion = JavaLanguageVersion.of(8)
}

kotlin {
    jvmToolchain(8)
}

// 定义 lintJarOutput，在 module_lint_aar 中被调用
configurations {
    lintJarOutput
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib"

    // 2x.x.x 版本
    // https://mvnrepository.com/artifact/com.android.tools.lint/lint-api
    implementation "com.android.tools.lint:lint-api:27.2.2"
    // https://mvnrepository.com/artifact/com.android.tools.lint/lint-checks
    implementation "com.android.tools.lint:lint-checks:27.2.2"

//    // 3x.x.x 版本，maven 镜像仓库里没有，google maven 代理也下载不下来
//    // https://mvnrepository.com/artifact/com.android.tools.lint/lint-api
//    implementation "com.android.tools.lint:lint-api:31.11.1"
//    // https://mvnrepository.com/artifact/com.android.tools.lint/lint-checks
//    implementation "com.android.tools.lint:lint-checks:31.11.1"

//    // 3x.x.x 版本，jar 方式
//    // https://mvnrepository.com/artifact/com.android.tools.lint/lint-api
//    implementation files('libs/lint-api-31.7.2.jar')
//    // https://mvnrepository.com/artifact/com.android.tools.lint/lint-checks
//    implementation files('libs/lint-checks-31.7.2.jar')
//    // jar 方式 还需要依赖其它库
//    // https://mvnrepository.com/artifact/com.android.tools.external.com-intellij/intellij-core
//    implementation files('libs/intellij-core-31.7.2.jar')
//    // https://mvnrepository.com/artifact/com.android.tools.external.org-jetbrains/uast
//    implementation files('libs/uast-31.7.2.jar')

    // 将 jar 文件添加到 lintJarOutput
    lintJarOutput files(jar)
}

jar {
    manifest {
        // `Lint-Registry` 是 lint 的注册类
        // 注册 IssueRegistry 的实现类
        attributes('Lint-Registry': 'com.example.lint.MyIssueRegistry')
    }
}
