// https://developer.android.com/build
// https://plugins.gradle.org/
plugins {
    id "com.android.application" // agp
    id "org.jetbrains.kotlin.android" // kotlin
    id "kotlin-parcelize"
    id "kotlin-kapt"
    id "com.google.devtools.ksp"
}

apply from: "../config_source.gradle"

String composeBoMVersion = "2024.12.01"

def time = new Date()

def gitCommitCount = executeCmd("git rev-list --count HEAD")?.toInteger() ?: 1
def gitLastTag = executeCmd("git describe --tags --always") ?: "1.0"
def gitCommitId = executeCmd("git rev-parse --short HEAD") ?: "nocommitid"

static def executeCmd(String cmd) {
    try {
        def process = cmd.execute()
        process.waitFor()
        def result = process.text.trim()
        return result
    } catch (e) {
        println(e)
        return null
    }
}

android {
    namespace 'com.example.wan.android'
    // 确定编译应用时，项目代码可以使用哪些 API。不影响应用运行时的行为，只影响编译时可以访问到哪些类和方法
    compileSdk 35

    defaultConfig {
        applicationId "com.example.wan.android"
        minSdk 21
        // 指定应用在运行时目标的 Android 版本。不影响可以使用的 API，而是影响应用在运行时的行为
        targetSdk 35
        versionCode gitCommitCount
        versionName gitLastTag // 假如每个 tag 都是一个 release

        multiDexEnabled true

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

//        resConfigs "zh"
        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86_64'
        }

        buildConfigField "String", "COMMIT_ID", "\"${gitCommitId}\""
        buildConfigField "String", "BUILD_TIME", "\"${time.time}\""
        buildConfigField "String", "OS_ARCH", "\"${System.properties['os.arch']}\""
        // On Java 11 (11.0.15) and Java 17 (17.0.3), System.getProperty("os.name") returns Windows 11, but "os.version" still reports 10.0
        buildConfigField "String", "OS_NAME", "\"${System.properties['os.name']}\""
        buildConfigField "String", "USER_NAME", "\"${System.properties['user.name']}\""
        buildConfigField "String", "GRADLE_VERSION", "\"${gradle.gradleVersion}\""
        buildConfigField "String", "GRADLE_JDK", "\"${System.properties['java.version']}\""
        buildConfigField "String", "JAVA_JVM", "\"1.8\"" // 对应 compileOptions
        buildConfigField "String", "KOTLIN_JVM", "\"1.8\"" // 对应 kotlinOptions
        buildConfigField "String", "KOTLIN_VERSION", "\"${kotlin_version}\""
        buildConfigField "String", "COMPOSE_VERSION", "\"${composeBoMVersion}\""

        vectorDrawables {
            useSupportLibrary true
        }
    }

//    ndkVersion project.properties.ndkVersion

    signingConfigs {
        config {
            storeFile file(rootProject.ext.sign.filePath)
            storePassword rootProject.ext.sign.storePassword
            keyAlias rootProject.ext.sign.keyAlias
            keyPassword rootProject.ext.sign.keyPassword
        }
    }

    // https://developer.android.com/build/build-variants
    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.config
        }
        release {
            debuggable false
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.config
        }
    }
    android.applicationVariants.all { variant ->
        variant.outputs.all {
            def flavorType = variant.productFlavors.collect { it.name.capitalize() }.join() + variant.buildType.name.capitalize() // 格式 GithubRelease
            def name
            if (variant.productFlavors[0].name == "github") {
                // 与 github actions 脚本获取的名称对应
                name = ("${model.name}" +
                        "-${variant.buildType.name}" +
                        ".apk")
            } else {
                name = ("${model.name}" +
                        "_${variant.versionName}" +
                        "_${variant.versionCode}" +
//                        "_${variant.buildType.name}" +
                        "_${flavorType}" +
                        "_${gitCommitId}" +
                        "_${time.time}" +
                        ".apk")
            }
            println("${flavorType} outputFileName = ${name}")
            outputFileName = name
        }
    }
    // 变体、维度
    // https://developer.android.com/build/build-variants
    flavorDimensions += ["channel"] // 可以使用多个维度，最终构建的安装包会包含每个维度的一个变体
    productFlavors {
        // 维度1 渠道
        normal {
            dimension "channel"
            manifestPlaceholders = [app_channel: "\"${name}\""]
            buildConfigField "String", "APP_CHANNEL", "\"${name}\""
        }
        github {
            // github
            dimension "channel"
            applicationIdSuffix ".github"
            versionNameSuffix ".github"
            manifestPlaceholders = [app_channel: "\"${name}\""]
            buildConfigField "String", "APP_CHANNEL", "\"${name}\""
        }
    }

    // https://developer.android.com/build/jdks
    compileOptions {
        encoding "UTF-8"
        // 代码 的 java 编译版本
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        // 代码 的 kotlin 编译版本
        jvmTarget = '1.8'
    }
    kotlin {
        // gradle 项目构建的 java 和 kotlin 编译版本
        jvmToolchain(17) // 最低版本与 Gradle 版本有关
    }

    buildFeatures {
        buildConfig = true
//        aidl true
        viewBinding true
        compose = true
    }
    composeOptions {
        // KGP 要对应 android.composeOptions.kotlinCompilerExtensionVersion
        // compose-kotlin https://developer.android.com/jetpack/androidx/releases/compose-kotlin
        // 1.3.2 -> kotlin 1.7.20
        // 1.4.8 -> kotlin 1.8.22
        // 1.5.15 -> kotlin 1.9.25
        // Compose Compiler Gradle plugin -> kotlin 2.0.0+
        // https://developer.android.com/develop/ui/compose/compiler
        kotlinCompilerExtensionVersion = "1.5.15"
    }
    packagingOptions { // 这个块定义了打包相关的配置
        // 指定在构建 APK 或 AAR 时要排除的文件或路径
        // `AL2.0` 和 `LGPL2.1` 通常是许可证文件，可能在某些情况下不需要打包进最终的 APK 或 AAR 中
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }

    lint {
        // https://developer.android.google.cn/studio/write/lint?hl=zh-cn#snapshot
        // Lint 检测: `./gradlew lint`，可加变体: `./gradlew lintRelease`
        // baseline 忽略已有的 Lint 问题，Lint 只会报告自上次生成基准文件之后新增的
        // 如果要创建新基准，请手动删除该文件并再次运行 lint
        baseline = file("lint-baseline.xml")
        ignoreWarnings = true // true 忽略警告
        abortOnError false // false 遇到错误不停止
        textReport true // true 输出lint报告
    }
}

// https://developer.android.com/build/dependencies
// https://mvnrepository.com/
dependencies {
    configurations.configureEach {
        resolutionStrategy {
            // 强制指定版本
            // emoji2 1.4.0 需要 compileSdk 34
//            force 'androidx.emoji2:emoji2:1.3.0'
//            force 'androidx.emoji2:emoji2-views-helper:1.3.0'
        }
    }
    // 依赖项配置
    // https://developer.android.google.cn/studio/build/dependencies?hl=zh-cn&agpversion=4.0#dependency_configurations
    // Module
//    implementation project(":module_common")
    // Lib
    // `fileTree` 使用指定目录，libs 下所有的 jar aar
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'], exclude: [
//            'module_lint_aar-debug.aar' // 排除 lint 文件, 另外使用 lintChecks 引用
    ])
    // `files` 使用指定文件
//    implementation files('libs/module_lint_aar-debug.aar')
//    lintChecks files('libs/module_lint_aar-debug.aar')
//    implementation files('libs/module_lint_lib.jar')
    // `project` 使用指定模块
    // `lintChecks` 是 lint-checks 库的，Lint 专用
    //noinspection DependencyNotationArgument
    lintChecks project(':module_lint')

    // Test
    testImplementation "junit:junit:4.13.2"
    androidTestImplementation "androidx.test.ext:junit:1.2.1"
    androidTestImplementation "androidx.test.espresso:espresso-core:3.6.1"

    implementation "androidx.multidex:multidex:2.0.1"

    // Compose
    // Compose BoM
    // https://developer.android.com/jetpack/compose/bom
    // https://developer.android.com/develop/ui/compose/bom/bom-mapping
//    def composeBoMVersion = "2023.10.01"
//    def composeBoMVersion = "2024.01.00"
//    def composeBoMVersion = "2024.02.02"
//    def composeBoMVersion = "2024.03.00"
//    def composeBoMVersion = "2024.04.01"
//    def composeBoMVersion = "2024.05.00"
//    def composeBoMVersion = "2024.06.00"
//    def composeBoMVersion = "2024.08.00"
//    def composeBoMVersion = "2024.09.03"
//    def composeBoMVersion = "2024.10.01"
//    def composeBoMVersion = "2024.11.00"
//    def composeBoMVersion = "2024.12.01"
//    def composeBoMVersion = "2025.01.01"
//    def composeBoMVersion = "2025.02.00"
//    def composeBoMVersion = "2025.03.01"
//    def composeBoMVersion = "2025.04.01"
//    def composeBoMVersion = "2025.05.01"
//    def composeBoMVersion = "2025.06.00"
    implementation(platform("androidx.compose:compose-bom:${composeBoMVersion}"))
    androidTestImplementation(platform("androidx.compose:compose-bom:${composeBoMVersion}"))
    implementation("androidx.compose.runtime:runtime")
    implementation("androidx.activity:activity-compose")
    // Material
    implementation("androidx.compose.material:material")
    // Material Design 3
    implementation("androidx.compose.material3:material3")
    // the main APIs for the underlying toolkit systems
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-geometry")
    implementation("androidx.compose.ui:ui-graphics")
    implementation("androidx.compose.ui:ui-text")
    // Android Studio Preview support
    implementation("androidx.compose.ui:ui-tooling-preview")
    debugImplementation("androidx.compose.ui:ui-tooling")
    // UI Tests
    androidTestImplementation("androidx.compose.ui:ui-test-junit4")
    debugImplementation("androidx.compose.ui:ui-test-manifest")
    // Optional - Included automatically by material, only add when you need
    // the icons but not the material library (e.g. when using Material3 or a
    // custom design system based on Foundation)
    implementation("androidx.compose.material:material-icons-core")
    // Optional - Add full set of material icons
    implementation("androidx.compose.material:material-icons-extended")
    // Optional - Add window size utils
    implementation("androidx.compose.material3:material3-window-size-class")
    implementation("androidx.compose.ui:ui-util")
    implementation("androidx.compose.runtime:runtime-livedata")
    // Optional - Integration with ViewBinding
    implementation("androidx.compose.ui:ui-viewbinding")
    // animation
    implementation("androidx.compose.animation:animation")
    implementation("androidx.compose.animation:animation-core")
    implementation("androidx.compose.animation:animation-graphics")
    // Optional - Integration with RxJava
    implementation("androidx.compose.runtime:runtime-rxjava2")
    // Accompanist: Compose 的实验性 APIs
    // https://github.com/google/accompanist
    // compose drawable painter
    // https://github.com/google/accompanist/tree/main/drawablepainter
    implementation("com.google.accompanist:accompanist-drawablepainter:0.36.0")

    // Compose 图片视频加载
    // https://github.com/coil-kt/coil
    implementation(platform("io.coil-kt:coil-bom:2.4.0"))
    implementation("io.coil-kt:coil-compose")
    implementation("io.coil-kt:coil-gif")
    implementation("io.coil-kt:coil-video")

    // 图库
    // https://github.com/leavesCZY/Matisse
    implementation("io.github.leavesczy:matisse:1.1.4")

    // Android
    // KTX https://developer.android.com/kotlin/ktx
    implementation platform("org.jetbrains.kotlin:kotlin-bom:${kotlin_version}")
    implementation "com.google.android.material:material:1.12.0"
    implementation "androidx.appcompat:appcompat:1.7.0"
    // 1.16.0 需要 AGP 8.6.0+
    implementation "androidx.core:core-ktx:1.15.0"
    implementation "androidx.core:core-splashscreen:1.0.1"
    implementation "androidx.activity:activity-ktx:1.9.3"
    // 2.9.0 需要 AGP 8.6.0+
    def lifecycleVersion = "2.8.7"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:${lifecycleVersion}"
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:${lifecycleVersion}"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:${lifecycleVersion}"
    implementation "androidx.lifecycle:lifecycle-viewmodel-savedstate:${lifecycleVersion}"
    implementation "androidx.lifecycle:lifecycle-extensions:2.2.0" // 停止维护
    implementation "androidx.lifecycle:lifecycle-process:${lifecycleVersion}"
    implementation "androidx.lifecycle:lifecycle-service:${lifecycleVersion}"
    implementation "androidx.lifecycle:lifecycle-reactivestreams-ktx:${lifecycleVersion}"
    implementation "androidx.constraintlayout:constraintlayout:2.2.0"
    // viewpager2 1.1 新特性 registerFragmentTransactionCallback
    implementation "androidx.viewpager2:viewpager2:1.1.0"
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:${lifecycleVersion}") // compose
    // 2.9.0 需要 AGP 8.6.0+
    def navigationVersion = "2.8.9"
    implementation "androidx.navigation:navigation-fragment-ktx:${navigationVersion}"
    implementation "androidx.navigation:navigation-ui-ktx:${navigationVersion}"
    implementation("androidx.navigation:navigation-compose:${navigationVersion}") // compose
    implementation "androidx.palette:palette-ktx:1.0.0"
    implementation "androidx.sqlite:sqlite-ktx:2.4.0"
    // https://developer.android.com/jetpack/androidx/releases/datastore
    implementation("androidx.datastore:datastore:1.1.1") // datastore
    implementation("androidx.datastore:datastore-preferences:1.1.1") // preferences datastore
    // https://developer.android.com/jetpack/androidx/releases/room
    def roomVersion = "2.6.1"
    implementation("androidx.room:room-runtime:${roomVersion}")
    implementation("androidx.room:room-ktx:${roomVersion}")
//    kapt("androidx.room:room-compiler:${roomVersion}")
    ksp("androidx.room:room-compiler:${roomVersion}")
    testImplementation("androidx.room:room-testing:${roomVersion}")
    implementation "androidx.work:work-runtime-ktx:2.10.0"
    implementation("androidx.paging:paging-runtime-ktx:3.3.4")
    implementation("androidx.paging:paging-compose:3.3.4") // paging compose
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"
    // 快乐库 - 扩展
    // https://github.com/LouisCAD/Splitties
    def splittiesVersion = "3.0.0"
    implementation "com.louiscad.splitties:splitties-fun-pack-android-base:${splittiesVersion}"
    implementation "com.louiscad.splitties:splitties-fun-pack-android-base-with-views-dsl:${splittiesVersion}"
    implementation "com.louiscad.splitties:splitties-fun-pack-android-appcompat:${splittiesVersion}"
    implementation "com.louiscad.splitties:splitties-fun-pack-android-appcompat-with-views-dsl:${splittiesVersion}"
    implementation "com.louiscad.splitties:splitties-fun-pack-android-material-components:${splittiesVersion}"
    implementation "com.louiscad.splitties:splitties-fun-pack-android-material-components-with-views-dsl:${splittiesVersion}"
    // 快乐库 - 工具
    // https://github.com/Blankj/AndroidUtilCode
    implementation "com.blankj:utilcodex:1.31.1"
    // 沉浸状态栏
    // https://github.com/gyf-dev/ImmersionBar
    implementation "com.geyifeng.immersionbar:immersionbar:3.2.2"
    implementation "com.geyifeng.immersionbar:immersionbar-ktx:3.2.2"
    // gson
    implementation "com.google.code.gson:gson:2.10.1"
    // 网络
    // https://github.com/square/okhttp
    implementation "com.squareup.okhttp3:okhttp:4.12.0"
    // https://github.com/square/retrofit
    def retrofitVersion = "2.11.0"
    implementation "com.squareup.retrofit2:retrofit:${retrofitVersion}"
    implementation "com.squareup.retrofit2:converter-gson:${retrofitVersion}"
    implementation "com.squareup.retrofit2:converter-scalars:${retrofitVersion}"
    // https://github.com/franmontiel/PersistentCookieJar
    implementation "com.github.franmontiel:PersistentCookieJar:v1.0.1"
    // 数据库
    // https://github.com/guolindev/LitePal
    implementation "org.litepal.guolindev:core:3.2.3"
    // 图片
    // https://github.com/bumptech/glide
    // https://bumptech.github.io/glide/doc/download-setup.html#kotlin---ksp
    def glideVersion = "4.16.0"
    implementation "com.github.bumptech.glide:glide:${glideVersion}"
//    kapt "com.github.bumptech.glide:compiler:${glideVersion}"
    ksp "com.github.bumptech.glide:ksp:${glideVersion}"
    implementation "com.github.bumptech.glide:okhttp3-integration:${glideVersion}"
    implementation("com.github.bumptech.glide:compose:1.0.0-beta01") // compose
    // https://github.com/wasabeef/glide-transformations
    implementation "jp.wasabeef:glide-transformations:4.3.0"
    // 权限
    // https://github.com/guolindev/PermissionX
    implementation "com.guolindev.permissionx:permissionx:1.8.1"
    // 消息
    // https://github.com/JeremyLiao/LiveEventBus
//    implementation "io.github.jeremyliao:live-event-bus-x:1.8.0"
    // https://github.com/michaellee123/LiveEventBus
    implementation "com.github.michaellee123:LiveEventBus:1.8.14" // 适配 Android 14
    // 快乐库 - UI
    // https://github.com/RuffianZhong/RWidgetHelper
    implementation "com.github.RuffianZhong:RWidgetHelper:androidx.v0.0.14"
    // RecyclerView ItemDecoration
    // https://github.com/grzegorzojdana/SpacingItemDecoration
    implementation "com.github.grzegorzojdana:SpacingItemDecoration:1.1.0"
    // https://github.com/square/leakcanary
//    debugImplementation "com.squareup.leakcanary:leakcanary-android:2.12" // 只要我不用 leakcanary 就不会有内存泄漏
    // 通过委托 自动处理 `Fragment.onDestroyView()` 时的 `viewBinding = null` 防止内存泄漏
    // https://github.com/androidbroadcast/ViewBindingPropertyDelegate
    implementation "com.github.kirich1409:viewbindingpropertydelegate-full:1.5.9"
//    implementation "com.github.kirich1409:viewbindingpropertydelegate-noreflection:1.5.9"

    // https://github.com/youth5201314/banner
    implementation "io.github.youth5201314:banner:2.2.2"

    // 弹窗
    // https://github.com/li-xiaojun/XPopup
    implementation("com.github.li-xiaojun:XPopup:2.9.19") {
        exclude group: "com.davemorrissey.labs", module: "subsampling-scale-image-view-androidx"
    }

    // 刷新
    // https://github.com/scwang90/SmartRefreshLayout
    def refreshVersion = "2.0.6"
    implementation "io.github.scwang90:refresh-layout-kernel:${refreshVersion}"      //核心必须依赖
    implementation "io.github.scwang90:refresh-header-classics:${refreshVersion}"    //经典刷新头
    implementation "io.github.scwang90:refresh-footer-classics:${refreshVersion}"    //经典加载
    implementation "io.github.scwang90:refresh-header-falsify:${refreshVersion}"     //虚拟刷新头
    implementation "io.github.scwang90:refresh-header-material:${refreshVersion}"    //谷歌刷新头
    implementation "io.github.scwang90:refresh-header-two-level:${refreshVersion}"   //二级刷新头

    // 流动布局 标签
    // https://github.com/hongyangAndroid/FlowLayout
    implementation "com.hyman:flowlayout-lib:1.1.2"

}
