name: Build APK and Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    environment: zjmok.jks # 指定环境，对应仓库 Settings 的 Environment secrets 中的 Environment 名称。若使用的是 Repository secrets 则不需要声明环境
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/use-secrets#storing-base64-binary-blobs-as-secrets
      # 解码 Base64 签名字符串到文件 release.jks
      - name: Decode signing keystore
        env:
          RELEASE_STORE_FILE_BASE64: ${{ secrets.RELEASE_STORE_FILE_BASE64 }}
        run: |
          if [ -n "$RELEASE_STORE_FILE_BASE64" ]; then
            echo "$RELEASE_STORE_FILE_BASE64" | base64 -d > release.jks
          fi
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembleGithubRelease
        env:
          # 将 Secrets 注入到 Gradle 可读取的环境变量
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/github/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
